version: '3.8'

services:

  postgres:
    image: postgres:14
    container_name: bank-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 996643
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: bank-app
    container_name: bank-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data: