server:
    port: 8080
spring:
    application:
        name: bank
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: 996643
        # url: jdbc:postgresql://postgres:5432/postgres
        url: jdbc:postgresql://localhost:5432/postgres
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file:
        name: /app/logs/bank.log
    level:
        root: INFO